spring:
  datasource:
    url: jdbc:mysql://localhost/buy4you
    username: buy4you
    password: buy4you
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect